export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const PUB_SUB = 'PUB_SUB';
export const NEW_PENDING_RESERVATION = 'NEW_PENDING_RESERVATION';
export const NEW_RESERVATION_UPDATE = 'NEW_RESERVATION_UPDATE';
